# Generated by Django 4.0.3 on 2022-03-10 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
            ],
            options={"verbose_name": "Genre", "verbose_name_plural": "Genres",},
        ),
        migrations.CreateModel(
            name="Writer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=250, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=250, verbose_name="Last Name"),
                ),
            ],
            options={"verbose_name": "Writer", "verbose_name_plural": "Writers",},
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                (
                    "synopsis",
                    models.TextField(max_length=5000, verbose_name="Synopsis"),
                ),
                ("release_date", models.DateTimeField(verbose_name="Release Date")),
                ("price", models.PositiveBigIntegerField(verbose_name="Price")),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.genre",
                        verbose_name="Genre",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.writer",
                        verbose_name="Writer",
                    ),
                ),
            ],
            options={"verbose_name": "Book", "verbose_name_plural": "Books",},
        ),
    ]
